sudo: true


language: python
python:
   - "2.7"


services:
   - docker


before_install:
   - docker pull mongo:latest
   - docker run -p 27017:27017 -d mongo
   - sleep 5
   - mongo --eval "printjson(db.serverStatus())"
   - mongo --eval 'db.adminCommand({setParameter:true, textSearchEnabled:true})' #http://stackoverflow.com/a/20673005/3448851
   - travis_wait java -jar selenium/selenium-server-standalone-3.4.0.jar

cache: pip

install:
   - pip install tox-travis
   - pip install codecov

script:
   - mongo --version
   - tox
   - if [ ${TRAVIS} ]; then  codecov -t "192b289d-b9a3-4179-873a-caedcb3f45a2";  fi